version: '3.3'

services:
  qrcode-backend:
    image: piads2022/qrcode-backend:1.0
    container_name: qrcode_backend
    restart: unless-stopped
    environment:
      PROFILE: homolog
    ports:
      - "8081:8081"
